# Generated by Django 5.2.1 on 2026-08-21 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('atm_type', models.CharField(blank=True, max_length=80)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('AVAILABLE', 'Available'), ('OFFLINE', 'Offline'), ('FAULT', 'Fault'), ('MAINTENANCE', 'Maintenance'), ('UNAVAILABLE', 'Unavailable'), ('DECOMMISSIONED', 'Decommissioned')], default='AVAILABLE', max_length=30)),
                ('assigned_team', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atms', to='organization.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
