# Generated by Django 5.2.1 on 2026-08-25 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='atm',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_atms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atm',
            name='communication_status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('FAULT', 'Fault'), ('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('MAINTENANCE', 'Maintenance'), ('ERROR', 'Error'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='atm',
            name='hardware_status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('FAULT', 'Fault'), ('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('MAINTENANCE', 'Maintenance'), ('ERROR', 'Error'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='atm',
            name='health',
            field=models.CharField(choices=[('HEALTHY', 'Healthy'), ('WARNING', 'Warning'), ('DEGRADED', 'Degraded'), ('CRITICAL', 'Critical'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], default='HEALTHY', max_length=20),
        ),
        migrations.AddField(
            model_name='atm',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atm',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atm',
            name='last_maintenance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atm',
            name='last_status_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atm',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='atm',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='atm',
            name='model',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='atm',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='atm',
            name='network_status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('FAULT', 'Fault'), ('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('MAINTENANCE', 'Maintenance'), ('ERROR', 'Error'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='atm',
            name='next_maintenance',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atm',
            name='power_status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('FAULT', 'Fault'), ('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('MAINTENANCE', 'Maintenance'), ('ERROR', 'Error'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='atm',
            name='serial_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='atm',
            name='status',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational'), ('AVAILABLE', 'Available'), ('OFFLINE', 'Offline'), ('UNAVAILABLE', 'Unavailable'), ('FAULT', 'Fault'), ('COMMUNICATION_PROBLEM', 'Communication Problem'), ('MAINTENANCE', 'Maintenance'), ('ERROR', 'Error'), ('DECOMMISSIONED', 'Decommissioned')], default='AVAILABLE', max_length=40),
        ),
        migrations.CreateModel(
            name='ATMStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('AVAILABLE', 'Available'), ('OFFLINE', 'Offline'), ('UNAVAILABLE', 'Unavailable'), ('FAULT', 'Fault'), ('COMMUNICATION_PROBLEM', 'Communication Problem'), ('MAINTENANCE', 'Maintenance'), ('ERROR', 'Error'), ('DECOMMISSIONED', 'Decommissioned')], max_length=40)),
                ('new_status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('AVAILABLE', 'Available'), ('OFFLINE', 'Offline'), ('UNAVAILABLE', 'Unavailable'), ('FAULT', 'Fault'), ('COMMUNICATION_PROBLEM', 'Communication Problem'), ('MAINTENANCE', 'Maintenance'), ('ERROR', 'Error'), ('DECOMMISSIONED', 'Decommissioned')], max_length=40)),
                ('reason', models.TextField(blank=True)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='assets.atm')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atm_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('CORRECTIVE', 'Corrective'), ('EMERGENCY', 'Emergency'), ('INSPECTION', 'Inspection'), ('NETWORK', 'Network'), ('HARDWARE', 'Hardware')], max_length=20)),
                ('reason', models.TextField()),
                ('work_performed', models.TextField(blank=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('STARTED', 'Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified')], default='SCHEDULED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='assets.atm')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ATMComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_type', models.CharField(choices=[('DISPLAY', 'Display'), ('CARD_READER', 'Card Reader'), ('CASH_DISPENSER', 'Cash Dispenser'), ('RECEIPT_PRINTER', 'Receipt Printer'), ('NETWORK', 'Network'), ('POWER', 'Power')], max_length=40)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('FAULT', 'Fault'), ('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('MAINTENANCE', 'Maintenance'), ('ERROR', 'Error'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('condition', models.CharField(choices=[('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('DEGRADED', 'Degraded'), ('FAULT', 'Fault'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='assets.atm')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('atm', 'component_type'), name='unique_component_per_atm')],
            },
        ),
    ]
