# Generated by Django 5.2.17 on 2026-08-26 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_atm_address_atm_assigned_technician_and_more'),
        ('incidents', '0002_escalation_priority_escalation_remarks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the ATM is part of active district operations.'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_jobs', to='incidents.incident'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='test_result',
            field=models.CharField(blank=True, choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='atm',
            name='communication_status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('FAULT', 'Fault'), ('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('MAINTENANCE', 'Maintenance'), ('ERROR', 'Error'), ('UNKNOWN', 'Unknown'), ('HEALTHY', 'Healthy')], default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='atm',
            name='hardware_status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('FAULT', 'Fault'), ('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('MAINTENANCE', 'Maintenance'), ('ERROR', 'Error'), ('UNKNOWN', 'Unknown'), ('HEALTHY', 'Healthy')], default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='atm',
            name='health',
            field=models.CharField(choices=[('HEALTHY', 'Healthy'), ('WARNING', 'Warning'), ('DEGRADED', 'Degraded'), ('CRITICAL', 'Critical'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance'), ('UNKNOWN', 'Unknown')], default='HEALTHY', max_length=20),
        ),
        migrations.AlterField(
            model_name='atm',
            name='network_status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('FAULT', 'Fault'), ('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('MAINTENANCE', 'Maintenance'), ('ERROR', 'Error'), ('UNKNOWN', 'Unknown'), ('HEALTHY', 'Healthy')], default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='atm',
            name='power_status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('FAULT', 'Fault'), ('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('MAINTENANCE', 'Maintenance'), ('ERROR', 'Error'), ('UNKNOWN', 'Unknown'), ('HEALTHY', 'Healthy')], default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='atm',
            name='status',
            field=models.CharField(choices=[('OPERATIONAL', 'Operational'), ('WARNING', 'Warning'), ('DEGRADED', 'Degraded'), ('FAULT', 'Fault'), ('OFFLINE', 'Offline'), ('CRITICAL', 'Critical'), ('MAINTENANCE', 'Maintenance'), ('UNDER_REPAIR', 'Under Repair'), ('UNKNOWN', 'Unknown')], default='OPERATIONAL', help_text='Technical / operational condition of the ATM.', max_length=40),
        ),
        migrations.AlterField(
            model_name='atmcomponent',
            name='condition',
            field=models.CharField(choices=[('HEALTHY', 'Healthy'), ('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('FAULT', 'Fault'), ('UNKNOWN', 'Unknown'), ('DEGRADED', 'Degraded'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='atmcomponent',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('FAULT', 'Fault'), ('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable'), ('MAINTENANCE', 'Maintenance'), ('ERROR', 'Error'), ('UNKNOWN', 'Unknown'), ('HEALTHY', 'Healthy')], default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='atmstatushistory',
            name='new_status',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='atmstatushistory',
            name='old_status',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('CORRECTIVE', 'Corrective'), ('EMERGENCY', 'Emergency'), ('INSPECTION', 'Inspection'), ('NETWORK', 'Network'), ('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software')], max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('SCHEDULED', 'Scheduled'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('UNDER_REPAIR', 'Under Repair'), ('TESTING', 'Testing'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified'), ('CANCELLED', 'Cancelled'), ('STARTED', 'Started')], default='REQUESTED', max_length=20),
        ),
    ]
