# Generated by Django 5.2.1 on 2026-09-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_atm_is_active_maintenance_incident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo of the ATM unit (front view or signage).', null=True, upload_to='atms/%Y/%m/'),
        ),
    ]
