# Generated by Django 5.2.17 on 2026-09-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_force_purge_demo_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmcomponent',
            name='component_type',
            field=models.CharField(choices=[('DISPLAY', 'Display'), ('CARD_READER', 'Card Reader'), ('CARD_TRANSPORT', 'Card Transport'), ('CASH_DISPENSER', 'Cash Dispenser'), ('CASH_CASSETTE', 'Cash Cassette'), ('REJECT_BIN', 'Reject Bin'), ('RECEIPT_PRINTER', 'Receipt Printer'), ('NETWORK', 'Network'), ('POWER', 'Power')], max_length=40),
        ),
    ]
