# Generated by Django 5.2.1 on 2026-08-21 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=60)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('ACKNOWLEDGED', 'Acknowledged'), ('ASSIGNED', 'Assigned'), ('INVESTIGATING', 'Investigating'), ('TROUBLESHOOTING', 'Troubleshooting'), ('RESOLVED', 'Resolved'), ('ESCALATED', 'Escalated'), ('VERIFICATION', 'Verification'), ('CLOSED', 'Closed')], default='REPORTED', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='assets.atm')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField()),
                ('technical_findings', models.TextField(blank=True)),
                ('required_team', models.CharField(max_length=150)),
                ('assigned_team', models.CharField(blank=True, max_length=150)),
                ('escalated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='incidents.incident')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('action_performed', models.TextField()),
                ('final_status', models.CharField(max_length=100)),
                ('resolved_at', models.DateTimeField()),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='incidents.incident')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TroubleshootingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.TextField()),
                ('observation', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('next_action', models.TextField(blank=True)),
                ('status', models.CharField(default='COMPLETED', max_length=30)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='incidents.incident')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('atm_available', models.BooleanField(default=False)),
                ('issue_cleared', models.BooleanField(default=False)),
                ('communication_working', models.BooleanField(default=False)),
                ('approved_test_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('resolution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='incidents.resolution')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
