# Generated by Django 5.2.1 on 2026-08-25 07:48

from django.db import migrations, models


def rename_verification_status(apps, schema_editor):
    Incident = apps.get_model("incidents", "Incident")
    Incident.objects.filter(status="VERIFICATION").update(status="VERIFIED")


def revert_verified_status(apps, schema_editor):
    Incident = apps.get_model("incidents", "Incident")
    Incident.objects.filter(status="VERIFIED").update(status="VERIFICATION")


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalation',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='escalation',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='escalation',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escalation',
            name='status',
            field=models.CharField(default='OPEN', max_length=30),
        ),
        migrations.AddField(
            model_name='escalation',
            name='troubleshooting_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='escalation_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='incident',
            name='final_result',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='service_impact',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='troubleshootingaction',
            name='action_type',
            field=models.CharField(choices=[('CHECK_ATM_STATUS', 'Check ATM Status'), ('PHYSICAL_INSPECTION', 'Physical Inspection'), ('CHECK_POWER', 'Check Power'), ('CHECK_CONNECTION', 'Check Connection'), ('CHECK_NETWORK', 'Check Network'), ('CHECK_COMMUNICATION', 'Check Communication'), ('CHECK_HARDWARE', 'Check Hardware'), ('CHECK_DISPLAY', 'Check Display'), ('CHECK_CARD_READER', 'Check Card Reader'), ('CHECK_CASH_DISPENSER', 'Check Cash Dispenser'), ('CHECK_RECEIPT_PRINTER', 'Check Receipt Printer'), ('RECORD_ERROR', 'Record Error'), ('PERFORM_AUTHORIZED_ACTION', 'Perform Authorized Action'), ('RETEST_ATM', 'Retest ATM'), ('VERIFY_SERVICE', 'Verify Service'), ('ESCALATE_INCIDENT', 'Escalate Incident')], default='CHECK_ATM_STATUS', max_length=40),
        ),
        migrations.AddField(
            model_name='troubleshootingaction',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('ACKNOWLEDGED', 'Acknowledged'), ('ASSIGNED', 'Assigned'), ('INVESTIGATING', 'Investigating'), ('TROUBLESHOOTING', 'Troubleshooting'), ('WAITING', 'Waiting'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('VERIFIED', 'Verified'), ('CLOSED', 'Closed')], default='REPORTED', max_length=30),
        ),
        migrations.RunPython(rename_verification_status, revert_verified_status),
    ]
