# Generated by Django 5.2.17 on 2026-08-26 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_atm_is_active_maintenance_incident_and_more'),
        ('incidents', '0002_escalation_priority_escalation_remarks_and_more'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='troubleshootingaction',
            name='action_type',
            field=models.CharField(choices=[('CHECK_STATUS', 'Check Status'), ('CHECK_ATM_STATUS', 'Check ATM Status'), ('PHYSICAL_INSPECTION', 'Physical Inspection'), ('CHECK_POWER', 'Check Power'), ('CHECK_CONNECTION', 'Check Connection'), ('CHECK_NETWORK', 'Check Network'), ('CHECK_COMMUNICATION', 'Check Communication'), ('CHECK_HARDWARE', 'Check Hardware'), ('CHECK_DISPLAY', 'Check Display'), ('CHECK_CARD_READER', 'Check Card Reader'), ('CHECK_CASH_DISPENSER', 'Check Cash Dispenser'), ('CHECK_RECEIPT_PRINTER', 'Check Receipt Printer'), ('CHECK_SOFTWARE_ERROR', 'Check Software Error'), ('RECORD_OBSERVATION', 'Record Observation'), ('RECORD_ERROR', 'Record Error'), ('AUTHORIZED_TROUBLESHOOTING', 'Authorized Troubleshooting'), ('PERFORM_AUTHORIZED_ACTION', 'Perform Authorized Action'), ('RETEST_ATM', 'Retest ATM'), ('VERIFY_SERVICE', 'Verify Service'), ('ESCALATE', 'Escalate'), ('ESCALATE_INCIDENT', 'Escalate Incident')], default='CHECK_ATM_STATUS', max_length=40),
        ),
        migrations.CreateModel(
            name='BranchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem_type', models.CharField(choices=[('NETWORK_COMMUNICATION', 'Network / Communication'), ('POWER', 'Power'), ('DISPLAY', 'Display'), ('CARD_READER', 'Card Reader'), ('CASH_DISPENSER', 'Cash Dispenser'), ('RECEIPT_PRINTER', 'Receipt Printer'), ('SOFTWARE', 'Software / Application'), ('HARDWARE', 'Hardware'), ('SECURITY', 'Security-Related Technical Issue'), ('GENERAL', 'General ATM Error'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=40)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('confirmed_severity', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], help_text='Severity confirmed by district operations (branch cannot force critical).', max_length=20)),
                ('atm_currently_working', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('description', models.TextField()),
                ('observed_error', models.TextField(blank=True)),
                ('problem_started_at', models.DateTimeField(blank=True, null=True)),
                ('customer_impact', models.CharField(blank=True, max_length=255)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='branch_reports/%Y/%m/')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('RECEIVED', 'Received'), ('REVIEWING', 'Reviewing'), ('CONVERTED_TO_INCIDENT', 'Converted to Incident'), ('ASSIGNED', 'Assigned'), ('RESOLVED', 'Resolved'), ('VERIFIED', 'Verified'), ('CLOSED', 'Closed'), ('REVIEWED', 'Reviewed'), ('DISMISSED', 'Dismissed')], default='SUBMITTED', max_length=40)),
                ('dismissal_reason', models.TextField(blank=True)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_reports', to='assets.atm')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atm_reports', to='organization.branch')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branch_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_branch_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='branch_report',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident', to='incidents.branchreport'),
        ),
    ]
