# Generated by Django 5.2.1 on 2026-09-03 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_alter_troubleshootingaction_action_type_branchreport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchreport',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='branch_reports/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'pdf', 'mp4', 'mov'])]),
        ),
    ]
