# Generated by Django 5.2.17 on 2026-09-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_alter_branchreport_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='category_detail',
            field=models.CharField(blank=True, help_text='Specific fault type within the category (e.g. Card jam, Reject bin full).', max_length=80),
        ),
        migrations.AlterField(
            model_name='branchreport',
            name='problem_type',
            field=models.CharField(choices=[('NETWORK_COMMUNICATION', 'Network / Communication'), ('POWER', 'Power'), ('DISPLAY', 'Display'), ('CARD_READER', 'Card Reader'), ('CARD_JAM', 'Card Jam'), ('CASH_DISPENSER', 'Cash Dispenser'), ('REJECT_BIN_FULL', 'Reject Bin Full'), ('CASH_CASSETTE_EMPTY', 'Cash Cassette Empty'), ('RECEIPT_PRINTER', 'Receipt Printer'), ('SOFTWARE', 'Software / Application'), ('HARDWARE', 'Hardware'), ('SECURITY', 'Security-Related Technical Issue'), ('GENERAL', 'General ATM Error'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=40),
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('HARDWARE', 'Hardware Fault'), ('CASH_OUT', 'Cash-out Fault'), ('LOST_COMMUNICATION', 'Lost Communication Fault'), ('OTHER', 'Other')], default='OTHER', max_length=40),
        ),
        migrations.AlterField(
            model_name='troubleshootingaction',
            name='action_type',
            field=models.CharField(choices=[('CHECK_STATUS', 'Check Status'), ('CHECK_ATM_STATUS', 'Check ATM Status'), ('PHYSICAL_INSPECTION', 'Physical Inspection'), ('CHECK_POWER', 'Check Power'), ('CHECK_CONNECTION', 'Check Connection'), ('CHECK_NETWORK', 'Check Network'), ('CHECK_COMMUNICATION', 'Check Communication'), ('CHECK_HARDWARE', 'Check Hardware'), ('CHECK_DISPLAY', 'Check Display'), ('CHECK_CARD_READER', 'Check Card Reader'), ('CHECK_CARD_TRANSPORT', 'Check Card Transport'), ('CHECK_CASH_DISPENSER', 'Check Cash Dispenser'), ('CHECK_CASH_CASSETTE', 'Check Cash Cassette'), ('CHECK_REJECT_BIN', 'Check Reject Bin'), ('CHECK_RECEIPT_PRINTER', 'Check Receipt Printer'), ('CHECK_SOFTWARE_ERROR', 'Check Software Error'), ('RECORD_OBSERVATION', 'Record Observation'), ('RECORD_ERROR', 'Record Error'), ('AUTHORIZED_TROUBLESHOOTING', 'Authorized Troubleshooting'), ('PERFORM_AUTHORIZED_ACTION', 'Perform Authorized Action'), ('RETEST_ATM', 'Retest ATM'), ('VERIFY_SERVICE', 'Verify Service'), ('ESCALATE', 'Escalate'), ('ESCALATE_INCIDENT', 'Escalate Incident')], default='CHECK_ATM_STATUS', max_length=40),
        ),
    ]
