# Generated by Django 5.2.17 on 2026-08-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_simplify_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DISTRICT_ADMIN', 'District Admin'), ('OPERATIONS_OFFICER', 'Operations Officer'), ('MAINTENANCE_SUPERVISOR', 'Maintenance Supervisor'), ('TECHNICIAN', 'Technician'), ('BRANCH_USER', 'Branch User'), ('AUDITOR', 'Auditor'), ('ADMINISTRATOR', 'Administrator'), ('SUPERVISOR', 'Supervisor'), ('MONITORING_OFFICER', 'Monitoring Officer')], default='AUDITOR', max_length=32),
        ),
    ]
