import {Link,useSearchParams} from 'react-router-dom'; import {useEffect,useState} from 'react'; import {useQuery} from '@tanstack/react-query'; import {api} from '../lib/api'; import {LoadingState,ErrorState,EmptyState} from '../components/feedback/StateView'; import {ResourceTable} from '../components/tables/ResourceTable'; import {StatusBadge,PriorityBadge} from '../components/ui/StatusBadge'; import {DistrictDialog,DistrictRowActions,DistrictRow} from '../components/organization/DistrictManager'; import {useAuth,hasPermission} from '../context/AuthContext';
type Kind='districts'|'branches'|'atms'|'incidents';
const INCIDENT_STATUSES=['REPORTED','ACKNOWLEDGED','ASSIGNED','INVESTIGATING','TROUBLESHOOTING','ESCALATED','RESOLVED','VERIFICATION','CLOSED'];
const titles={districts:'Districts',branches:'Branches',atms:'ATM monitoring',incidents:'Incident management'} as const;
const emptyMessages={districts:'No districts found in your authorized scope.',branches:'No branches found for your current scope.',atms:'No ATMs found for your current scope.',incidents:'No incidents found for your current scope.'} as const;
function useDebounced(value:string,delay=400){const [debounced,setDebounced]=useState(value);useEffect(()=>{const timer=setTimeout(()=>setDebounced(value),delay);return()=>clearTimeout(timer)},[value,delay]);return debounced}
export default function ResourcePage({kind}:{kind:Kind}){
const [search,setSearch]=useState('');const debouncedSearch=useDebounced(search);
const [status,setStatus]=useState('');
const {currentUser}=useAuth();
const [districtDialog,setDistrictDialog]=useState<{open:boolean;row:DistrictRow|null}>({open:false,row:null});
const effectiveStatus=kind==='incidents'?status:'';
const q=useQuery({queryKey:[kind,debouncedSearch,effectiveStatus],queryFn:async()=>{
const params=new URLSearchParams();
if(debouncedSearch)params.set('search',debouncedSearch);
if(effectiveStatus)params.set('status',effectiveStatus);
if(kind==='incidents')params.set('ordering','-created_at');
const query=params.toString();
const {data}=await api.get<({id:number}&Record<string,any>)[]>(`/${kind}/${query?`?${query}`:''}`);
return Array.isArray(data)?data:(data as {results:({id:number}&Record<string,any>)[]}).results},placeholderData:previous=>previous});
return <section className="resource-page"><div className="resource-head"><div><p className="eyebrow accent">OPERATIONS / {kind.toUpperCase()}</p><h1>{titles[kind]}</h1><p className="muted">Records returned by the Django API within your authorized scope.</p></div><div className="resource-actions"><input className="search-input" placeholder="Search records…" value={search} onChange={e=>setSearch(e.target.value)}/>{kind==='incidents'&&<select className="search-input" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{INCIDENT_STATUSES.map(s=><option key={s} value={s}>{s}</option>)}</select>}{kind==='districts'&&hasPermission(currentUser,'district.create')&&<button className="button primary" onClick={()=>setDistrictDialog({open:true,row:null})}>＋ New district</button>}<button className="button secondary" onClick={()=>q.refetch()}>↻ Refresh</button></div></div>
{districtDialog.open&&<DistrictDialog row={districtDialog.row} onClose={()=>setDistrictDialog({open:false,row:null})}/>}
<div className="panel resource-panel">{q.isLoading?<LoadingState label={`Loading ${kind}…`}/>:q.isError?<ErrorState message="Check your session and Django API connection."/>:(q.data||[]).length===0?<EmptyState title={emptyMessages[kind]}/>:kind==='districts'?<ResourceTable rows={q.data||[]} columns={[{key:'name',label:'District',render:r=><><strong>{r.name}</strong><small>{r.code}</small></>},{key:'branch_count',label:'Branches'},{key:'status',label:'Status',render:r=><StatusBadge value={r.status}/>},{key:'actions',label:'',render:r=><DistrictRowActions row={r as DistrictRow} onEdit={()=>setDistrictDialog({open:true,row:r as DistrictRow})}/>}]}/>:kind==='branches'?<ResourceTable rows={q.data||[]} columns={[{key:'name',label:'Branch',render:r=><><strong>{r.name}</strong><small>{r.code}</small></>},{key:'district_name',label:'District'},{key:'status',label:'Status',render:r=><StatusBadge value={r.status}/>}]}/>:kind==='atms'?<ResourceTable rows={q.data||[]} columns={[{key:'reference',label:'ATM'},{key:'branch_name',label:'Branch'},{key:'district_name',label:'District'},{key:'status',label:'Status',render:r=><StatusBadge value={r.status}/>}]}/>:<ResourceTable rows={q.data||[]} columns={[{key:'incident_id',label:'Incident',render:r=><Link to={`/incidents/${r.id}`}><strong>{r.incident_id}</strong><small>{r.title}</small></Link>},{key:'atm_reference',label:'ATM'},{key:'district_name',label:'District'},{key:'priority',label:'Priority',render:r=><PriorityBadge value={r.priority}/>},{key:'status',label:'Status',render:r=><StatusBadge value={r.status}/>} ]}/>}</div></section>}
