# Generated by Django 5.2.1 on 2026-08-21 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30)),
                ('branch_type', models.CharField(blank=True, max_length=60)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('SETUP', 'Under Setup'), ('ACTIVE', 'Active'), ('CLOSED', 'Temporarily Closed'), ('INACTIVE', 'Inactive')], default='SETUP', max_length=30)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='organization.district')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('district', 'code'), name='unique_branch_code_per_district')],
            },
        ),
    ]
