# Generated by Django 5.2.1 on 2026-09-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('setting_type', models.CharField(choices=[('STRING', 'String'), ('INT', 'Integer'), ('BOOL', 'Boolean'), ('JSON', 'JSON')], default='STRING', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
